apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-configmap
  namespace: sidecar-injector
data:
  sidecarconfig.yaml: |
    containers:
    - name: sidecar-mosn
      image: xxx/qqq/mosn:v1
      imagePullPolicy: Always
      ports:
      - containerPort: 80
      volumeMounts:
      - name: export
        mountPath: /export
    volumes:
    - name: export
      flexVolume:
        driver: kubernetes.io/lvm
        fsType: ext4
        options:
          size: 5Gi
          volumeID: newjdoslog_hc03new
          volumegroup: docker