apiVersion: v1
kind: ServiceAccount
imagePullSecrets:
  - name: mosn-sct
metadata:
  name: istio-sidecar-injector-service-account
  namespace: sidecar-injector
  labels:
    app: kube-mutating-webhook-tutorial
